import type {
  MandalaElementType,
  ArrowMotionType,
  ArrowTurns,
  MandalaColor,
} from "../enums/mandala-enums";
import { TKA_BLUE } from "./mandala-config";

/**
 * 2D point in canvas coordinates.
 */
export interface Point {
  x: number;
  y: number;
}

/**
 * Arrow type specification for loading the correct SVG.
 */
export interface ArrowSpec {
  motionType: ArrowMotionType;
  turns: ArrowTurns;
}

/**
 * Staff type specification.
 */
export interface StaffSpec {
  variant: "simple" | "detailed";
}

/**
 * Individual element placed on the mandala canvas.
 * This represents the "source" element that the user places.
 * Symmetry copies are generated from these source elements.
 */
export interface MandalaElement {
  /** Unique identifier */
  id: string;

  /** Type of element */
  type: MandalaElementType;

  /** Position in canvas coordinates (0-950) */
  position: Point;

  /** Rotation angle in degrees (0-360) */
  rotation: number;

  /** Scale factor (1.0 = 100%) */
  scale: number;

  /** Element color */
  color: MandalaColor;

  /** Arrow specification (if type is 'arrow') */
  arrowSpec?: ArrowSpec;

  /** Staff specification (if type is 'staff') */
  staffSpec?: StaffSpec;

  /** Cached SVG content (loaded asynchronously) */
  svgContent?: string;

  /** SVG viewBox dimensions */
  viewBox?: { width: number; height: number };

  /** SVG center point for rotation */
  center?: Point;

  /** Z-index for layering (higher = on top) */
  zIndex: number;

  /** Whether this element is currently selected */
  isSelected?: boolean;
}

/**
 * Result of applying a symmetry transformation to an element.
 * These are the "copies" generated by rotational/mirror symmetry.
 */
export interface TransformedElement {
  /** Reference to the source element ID */
  sourceId: string;

  /** Transformed position */
  position: Point;

  /** Transformed rotation (source rotation + symmetry rotation) */
  rotation: number;

  /** Scale (usually same as source) */
  scale: number;

  /** Whether this copy is mirrored */
  isMirrored: boolean;

  /** Which fold this copy belongs to (0 = source, 1-n = copies) */
  foldIndex: number;

  /** Cached SVG content (same as source, but may be color-transformed) */
  svgContent?: string;
}

/**
 * Serialized version for Firebase storage.
 */
export interface SerializedMandalaElement {
  id: string;
  type: MandalaElementType;
  position: { x: number; y: number };
  rotation: number;
  scale: number;
  color: MandalaColor;
  arrowSpec?: ArrowSpec;
  staffSpec?: StaffSpec;
  zIndex: number;
}

/**
 * Create a new mandala element with defaults.
 */
export function createMandalaElement(
  type: MandalaElementType,
  position: Point,
  overrides?: Partial<MandalaElement>
): MandalaElement {
  return {
    id: crypto.randomUUID(),
    type,
    position,
    rotation: 0,
    scale: 1,
    color: TKA_BLUE,
    zIndex: 0,
    ...overrides,
  };
}

/**
 * Serialize a mandala element for storage.
 */
export function serializeElement(
  element: MandalaElement
): SerializedMandalaElement {
  return {
    id: element.id,
    type: element.type,
    position: { x: element.position.x, y: element.position.y },
    rotation: element.rotation,
    scale: element.scale,
    color: element.color,
    arrowSpec: element.arrowSpec,
    staffSpec: element.staffSpec,
    zIndex: element.zIndex,
  };
}

/**
 * Deserialize a mandala element from storage.
 */
export function deserializeElement(
  data: SerializedMandalaElement
): MandalaElement {
  return {
    ...data,
    position: { x: data.position.x, y: data.position.y },
  };
}
